### ISSUE TITLE
Consider updating use of LinearGradient

### ISSUE THREAD

**Issue by dangdennis** [FiberJW/reason-expo#11]
Priority: Low

Issue: With the latest version of expo-cli, using ReasonExpo.LinearGradient returns this warning.
```
Running application on iPhone X.
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: LinearGradient.

1. Add correct versions of these packages to your project using:

   expo install expo-linear-gradient

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { LinearGradient } from 'expo' -> import { LinearGradient } from 'expo-linear-gradient'
```

Solution: 
Consider using another component or create bindings to use `expo-linear-gradient` directly to handle warning.

**Comment by FiberJW** [comment]
Hey, thanks for your input! Would you mind submitting a PR with a fix for that in both the src/package.json, src/LinearGradient.re, and template/package.json? That would be a big help ❤️

**Comment by dangdennis** [comment]
Definitely will. I wanted to make sure you’re good with the change!
