### ISSUE TITLE
Quite a lot of mandatory props for Camera-component

### ISSUE THREAD

**Issue by mikaello** [FiberJW/reason-expo#13]
I am using `v33.1.0` of this library, created with `expo init <PROJECT_NAME> --template expo-template-reason`.

When creating a `Camera`-component, it seems that you have to provide all props except for `barCodeScannerSettings` and `style`, this makes it 14 mandatory props, and for most of them I want default. Here is a minimal implementation of an app using camera component:

```reasonml
open BsReactNative;

let component = ReasonReact.statelessComponent("App");

let make = _children => {
  ...component,
  didMount: _self => {
    ReasonExpo.Permissions.askAsync(ReasonExpo.Permissions.Camera)
    |> Js.Promise.then_(value => {
         Js.log(value);
         Js.Promise.resolve(value);
       });
    ();
  },
  render: _self =>
    <ReasonExpo.Camera
      onFacesDetected={_val => Js.log("face detection fired")}
      faceDetectionMode=ReasonExpo.Camera.Accurate
      faceDetectionLandmarks=ReasonExpo.Camera.None
      faceDetectionClassifications=ReasonExpo.Camera.None
      onMountError={error => Js.log({j|"error $error"|j})}
      flashMode=ReasonExpo.Camera.Off
      autoFocus=ReasonExpo.Camera.On
      zoom=0.
      whiteBalance=ReasonExpo.Camera.Auto
      focusDepth=0.
      ratio="16:9"
      onCameraReady=Js.log
      type_=ReasonExpo.Camera.Back
      onBarCodeScanned={value => {
        let data = value##data;
        //let valueType = value##_type; // Does not work: This expression has type {. data: string, type: string} It has no method _type

        Js.log({j|barcode $data |j});
      }}
      style=StyleSheet.absoluteFillObject>
      <Text> {React.string("This is a cameratest")} </Text>
    </ReasonExpo.Camera>,
};

let default = ReasonReact.wrapReasonForJs(~component, _jsProps => make([||]));
```

... and that seems like a lot to just get the camera up and running with basic properties.

If I remove any of the props in the camera-component, e.g. `flashMode`, I get an error like:
```
Error: This expression has type
         (~flashMode: ReasonExpo.Camera.flashMode) =>
         ReasonReact.component(ReasonReact.stateless,
                                ReasonReact.noRetainedProps,
                                ReasonReact.actionless)
       but an expression was expected of type
         ReasonReact.component('a, 'b, 'c) =
           ReasonReact.componentSpec('a, 'a, 'b, 'b, 'c)
```

I understand that it may be easier to have the component in this way, to be able to use it without sending in optionals all the time, but it is quite a lot of work to take a stand to all of those props if you're just interested in basic camera functionality.

Is the intentention that it should be used in this way, or am I missing something?

**Comment by FiberJW** [comment]
It wasn't intentional, it was just the easiest way to bind the props for this component at the time of writing. I was adding a bunch of API bindings at the time, so a few decisions like optional props may have been overlooked. If you could send a PR with optional prop types that'd be much appreciated!

**Comment by mikaello** [comment]
Thanks for the fast reply!

I checked out the other bindings in this repo, and it looks like you have given most of them default values for props, e.g. [`Video`](https://github.com/FiberJW/reason-expo/blob/f24656ecbd5ee0c4de8e4d8235730c796bdd4005/src/Video.re) have default values for all props. This seems like a better solution than adding optionals.

If you don't mind I could figure out the default values in Expo, add these to the `Camera`-component in this repo and send a PR when ready.

Thanks for the great work, quite a large job to add all these bindings!
