### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by bstro** [FiberJW/reason-expo#5]
I've tried a couple of times to figure out how to create the necessary typedefs to support `Expo.Svg` to no avail (I'm a bit of a noob, both to Reason, Expo, and app development in general). Any chance there are plans to cover this API?

**Comment by FiberJW** [comment]
@bstro I just completed cooking up some SVG bindings for Expo. If anything needs to be tweaked or fixed, feel free to send a PR my way!

**Comment by bstro** [comment]
Wow! Incredible. I'm extremely appreciative.
